### ISSUE TITLE
Question: Graph depth first traversal

### ISSUE THREAD

**Issue by Jaxwood** [kuychaco/algoClass#7]
Hi,

Thanks you for these execises!

I have a question about graph depth first traversal - I don't understand why the distance for 4 is 2 in the below example taken from graph.js. I would expect it to be `4, 1` since it is only 1 away from 1.

Example Usage:
1---2---3---5
 \ /
  4
{
  '1': [ 2, 4 ],
  '2': [ 1, 3, 4 ],
  '3': [ 2, 5 ],
  '4': [ 1, 2 ],
  '5': [ 3 ]
}
var traverseDF = [];
graph.traverseDepthFirst(1, function(val, distance) { traverseDF.push([val, distance]) });
traverseDF should be [ [ 1, 0 ], [ 2, 1 ], [ 3, 2 ], [ 5, 3 ], `[ 4, 2 ]` ]

**Comment by RebootJeff** [comment]
Maybe @kuychaco can correct me if I'm wrong, but I think this has to do with the *Depth-First* nature of the traversal. The algorithm will go through node "2" before in order to hit node "4". Therefore, the algorithm will yield a distance of 2. In other words, you're seeing a limitation of using depth-first traversal. It doesn't give you the shortest distance, it gives you the "depth-first distance" (so to speak).

The same "problem" arises with breadth-first traversal. Each algorithm explores only 1 path from one node to another node. In a complex graph, there could easily be a slew of paths from one node to another, so you'd have to find a way to compare those multiple paths. In other words, you need a separate algorithm to find the shortest distance ...which is [the bonus exercise](https://github.com/kuychaco/algoClass/blob/solutions/data-structures/graph.js#L87). There is no solution provided, but Google knows the answer 😉
